/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
define(["require", "exports"], function (require, exports) {
    "use strict";
    var Connector;
    (function (Connector) {
        (function (TypeEnum) {
            TypeEnum[TypeEnum["HTTP"] = 'HTTP'] = "HTTP";
            TypeEnum[TypeEnum["FTP"] = 'FTP'] = "FTP";
            TypeEnum[TypeEnum["RTSP"] = 'RTSP'] = "RTSP";
        })(Connector.TypeEnum || (Connector.TypeEnum = {}));
        var TypeEnum = Connector.TypeEnum;
    })(Connector = exports.Connector || (exports.Connector = {}));
});
