/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import * as models from './models';
export interface DeviceInfo extends models.Item {
    roles?: Array<string>;
    deviceType?: string;
    macAddress?: string;
    extraInformation?: Array<string>;
    operaProxy?: boolean;
    lastLoginIpAddress?: string;
    model?: string;
    location?: string;
    lastLoginDate?: Date;
    secret?: string;
    subLocation?: string;
    status?: string;
}
