/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
define(["require", "exports"], function (require, exports) {
    "use strict";
    var Grants;
    (function (Grants) {
        (function (GrantsEnum) {
            GrantsEnum[GrantsEnum["AUTHENTICATE"] = 'AUTHENTICATE'] = "AUTHENTICATE";
            GrantsEnum[GrantsEnum["ADMIN"] = 'ADMIN'] = "ADMIN";
            GrantsEnum[GrantsEnum["UPLOAD"] = 'UPLOAD'] = "UPLOAD";
            GrantsEnum[GrantsEnum["ENTITYVIEW"] = 'ENTITY_VIEW'] = "ENTITYVIEW";
            GrantsEnum[GrantsEnum["ENTITYCREATE"] = 'ENTITY_CREATE'] = "ENTITYCREATE";
            GrantsEnum[GrantsEnum["ENTITYEDIT"] = 'ENTITY_EDIT'] = "ENTITYEDIT";
            GrantsEnum[GrantsEnum["ENTITYDELETE"] = 'ENTITY_DELETE'] = "ENTITYDELETE";
            GrantsEnum[GrantsEnum["ITEMVIEW"] = 'ITEM_VIEW'] = "ITEMVIEW";
            GrantsEnum[GrantsEnum["ITEMCREATE"] = 'ITEM_CREATE'] = "ITEMCREATE";
            GrantsEnum[GrantsEnum["ITEMEDIT"] = 'ITEM_EDIT'] = "ITEMEDIT";
            GrantsEnum[GrantsEnum["ITEMDELETE"] = 'ITEM_DELETE'] = "ITEMDELETE";
            GrantsEnum[GrantsEnum["ITEMPUBLISH"] = 'ITEM_PUBLISH'] = "ITEMPUBLISH";
            GrantsEnum[GrantsEnum["FILEDOWNLOAD"] = 'FILE_DOWNLOAD'] = "FILEDOWNLOAD";
            GrantsEnum[GrantsEnum["FIELDVIEW"] = 'FIELD_VIEW'] = "FIELDVIEW";
            GrantsEnum[GrantsEnum["FIELDEDIT"] = 'FIELD_EDIT'] = "FIELDEDIT";
        })(Grants.GrantsEnum || (Grants.GrantsEnum = {}));
        var GrantsEnum = Grants.GrantsEnum;
        (function (FieldGrantsEnum) {
            FieldGrantsEnum[FieldGrantsEnum["AUTHENTICATE"] = 'AUTHENTICATE'] = "AUTHENTICATE";
            FieldGrantsEnum[FieldGrantsEnum["ADMIN"] = 'ADMIN'] = "ADMIN";
            FieldGrantsEnum[FieldGrantsEnum["UPLOAD"] = 'UPLOAD'] = "UPLOAD";
            FieldGrantsEnum[FieldGrantsEnum["ENTITYVIEW"] = 'ENTITY_VIEW'] = "ENTITYVIEW";
            FieldGrantsEnum[FieldGrantsEnum["ENTITYCREATE"] = 'ENTITY_CREATE'] = "ENTITYCREATE";
            FieldGrantsEnum[FieldGrantsEnum["ENTITYEDIT"] = 'ENTITY_EDIT'] = "ENTITYEDIT";
            FieldGrantsEnum[FieldGrantsEnum["ENTITYDELETE"] = 'ENTITY_DELETE'] = "ENTITYDELETE";
            FieldGrantsEnum[FieldGrantsEnum["ITEMVIEW"] = 'ITEM_VIEW'] = "ITEMVIEW";
            FieldGrantsEnum[FieldGrantsEnum["ITEMCREATE"] = 'ITEM_CREATE'] = "ITEMCREATE";
            FieldGrantsEnum[FieldGrantsEnum["ITEMEDIT"] = 'ITEM_EDIT'] = "ITEMEDIT";
            FieldGrantsEnum[FieldGrantsEnum["ITEMDELETE"] = 'ITEM_DELETE'] = "ITEMDELETE";
            FieldGrantsEnum[FieldGrantsEnum["ITEMPUBLISH"] = 'ITEM_PUBLISH'] = "ITEMPUBLISH";
            FieldGrantsEnum[FieldGrantsEnum["FILEDOWNLOAD"] = 'FILE_DOWNLOAD'] = "FILEDOWNLOAD";
            FieldGrantsEnum[FieldGrantsEnum["FIELDVIEW"] = 'FIELD_VIEW'] = "FIELDVIEW";
            FieldGrantsEnum[FieldGrantsEnum["FIELDEDIT"] = 'FIELD_EDIT'] = "FIELDEDIT";
        })(Grants.FieldGrantsEnum || (Grants.FieldGrantsEnum = {}));
        var FieldGrantsEnum = Grants.FieldGrantsEnum;
    })(Grants = exports.Grants || (exports.Grants = {}));
});
