/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ItemMeta {
    state?: ItemMeta.StateEnum;

    validity?: ItemMeta.ValidityEnum;

    validityErrors?: Array<models.ValidityError>;

    security?: ItemMeta.SecurityEnum;

    securityErrors?: Array<models.SecurityError>;

}
export namespace ItemMeta {
    export enum StateEnum {
        OK = <any> 'OK',
        ERROR = <any> 'ERROR'
    }
    export enum ValidityEnum {
        VALID = <any> 'VALID',
        INVALID = <any> 'INVALID',
        UNKNOWN = <any> 'UNKNOWN'
    }
    export enum SecurityEnum {
        ALLOWED = <any> 'ALLOWED',
        FORBIDDEN = <any> 'FORBIDDEN',
        UNKNOWN = <any> 'UNKNOWN'
    }
}
