/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
define(["require", "exports"], function (require, exports) {
    "use strict";
    var ItemMeta;
    (function (ItemMeta) {
        (function (StateEnum) {
            StateEnum[StateEnum["OK"] = 'OK'] = "OK";
            StateEnum[StateEnum["ERROR"] = 'ERROR'] = "ERROR";
        })(ItemMeta.StateEnum || (ItemMeta.StateEnum = {}));
        var StateEnum = ItemMeta.StateEnum;
        (function (ValidityEnum) {
            ValidityEnum[ValidityEnum["VALID"] = 'VALID'] = "VALID";
            ValidityEnum[ValidityEnum["INVALID"] = 'INVALID'] = "INVALID";
            ValidityEnum[ValidityEnum["UNKNOWN"] = 'UNKNOWN'] = "UNKNOWN";
        })(ItemMeta.ValidityEnum || (ItemMeta.ValidityEnum = {}));
        var ValidityEnum = ItemMeta.ValidityEnum;
        (function (SecurityEnum) {
            SecurityEnum[SecurityEnum["ALLOWED"] = 'ALLOWED'] = "ALLOWED";
            SecurityEnum[SecurityEnum["FORBIDDEN"] = 'FORBIDDEN'] = "FORBIDDEN";
            SecurityEnum[SecurityEnum["UNKNOWN"] = 'UNKNOWN'] = "UNKNOWN";
        })(ItemMeta.SecurityEnum || (ItemMeta.SecurityEnum = {}));
        var SecurityEnum = ItemMeta.SecurityEnum;
    })(ItemMeta = exports.ItemMeta || (exports.ItemMeta = {}));
});
