/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Message extends models.Item {
    date?: number;

    fidelioId?: number;

    attachments?: string;

    read?: number;

    toDeviceId?: string;

    subject?: string;

    externalId?: number;

    priority?: number;

    body?: string;

    creationDate?: number;

    internalLink?: string;

    messageType?: string;

    from?: string;

    time?: number;

    toRoomNumber?: string;

    toReservationNumber?: number;

}
