/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
define(["require", "exports"], function (require, exports) {
    "use strict";
    var OwnTenantEntityFilter;
    (function (OwnTenantEntityFilter) {
        (function (ModeEnum) {
            ModeEnum[ModeEnum["OWN"] = 'OWN'] = "OWN";
            ModeEnum[ModeEnum["OWNANDCHILDREN"] = 'OWN_AND_CHILDREN'] = "OWNANDCHILDREN";
            ModeEnum[ModeEnum["OWNANDPARENTS"] = 'OWN_AND_PARENTS'] = "OWNANDPARENTS";
            ModeEnum[ModeEnum["OWNANDPARENTANDCHILDREN"] = 'OWN_AND_PARENT_AND_CHILDREN'] = "OWNANDPARENTANDCHILDREN";
            ModeEnum[ModeEnum["CHILDREN"] = 'CHILDREN'] = "CHILDREN";
            ModeEnum[ModeEnum["PARENTS"] = 'PARENTS'] = "PARENTS";
            ModeEnum[ModeEnum["PARENTSANDCHILDREN"] = 'PARENTS_AND_CHILDREN'] = "PARENTSANDCHILDREN";
        })(OwnTenantEntityFilter.ModeEnum || (OwnTenantEntityFilter.ModeEnum = {}));
        var ModeEnum = OwnTenantEntityFilter.ModeEnum;
    })(OwnTenantEntityFilter = exports.OwnTenantEntityFilter || (exports.OwnTenantEntityFilter = {}));
});
