/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var QueryStringQuery;
    (function (QueryStringQuery) {
        let DefaultOperatorEnum;
        (function (DefaultOperatorEnum) {
            DefaultOperatorEnum[DefaultOperatorEnum["OR"] = 'OR'] = "OR";
            DefaultOperatorEnum[DefaultOperatorEnum["AND"] = 'AND'] = "AND";
        })(DefaultOperatorEnum = QueryStringQuery.DefaultOperatorEnum || (QueryStringQuery.DefaultOperatorEnum = {}));
    })(QueryStringQuery = exports.QueryStringQuery || (exports.QueryStringQuery = {}));
});
