/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var Role;
    (function (Role) {
        let VirtualHostDependencyEnum;
        (function (VirtualHostDependencyEnum) {
            VirtualHostDependencyEnum[VirtualHostDependencyEnum["NONE"] = 'NONE'] = "NONE";
            VirtualHostDependencyEnum[VirtualHostDependencyEnum["DIRECT"] = 'DIRECT'] = "DIRECT";
            VirtualHostDependencyEnum[VirtualHostDependencyEnum["FULL"] = 'FULL'] = "FULL";
        })(VirtualHostDependencyEnum = Role.VirtualHostDependencyEnum || (Role.VirtualHostDependencyEnum = {}));
    })(Role = exports.Role || (exports.Role = {}));
});
