/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
define(["require", "exports"], function (require, exports) {
    "use strict";
    var SearchRequest;
    (function (SearchRequest) {
        (function (SearchModeEnum) {
            SearchModeEnum[SearchModeEnum["DEFAULT"] = 'DEFAULT'] = "DEFAULT";
            SearchModeEnum[SearchModeEnum["TRASH"] = 'TRASH'] = "TRASH";
            SearchModeEnum[SearchModeEnum["ALL"] = 'ALL'] = "ALL";
        })(SearchRequest.SearchModeEnum || (SearchRequest.SearchModeEnum = {}));
        var SearchModeEnum = SearchRequest.SearchModeEnum;
    })(SearchRequest = exports.SearchRequest || (exports.SearchRequest = {}));
});
