/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var Sort;
    (function (Sort) {
        let OrderEnum;
        (function (OrderEnum) {
            OrderEnum[OrderEnum["ASC"] = 'ASC'] = "ASC";
            OrderEnum[OrderEnum["DESC"] = 'DESC'] = "DESC";
            OrderEnum[OrderEnum["NONE"] = 'NONE'] = "NONE";
        })(OrderEnum = Sort.OrderEnum || (Sort.OrderEnum = {}));
        let MissingEnum;
        (function (MissingEnum) {
            MissingEnum[MissingEnum["FIRST"] = 'FIRST'] = "FIRST";
            MissingEnum[MissingEnum["LAST"] = 'LAST'] = "LAST";
        })(MissingEnum = Sort.MissingEnum || (Sort.MissingEnum = {}));
    })(Sort = exports.Sort || (exports.Sort = {}));
});
