/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
define(["require", "exports"], function (require, exports) {
    "use strict";
    var TermsAggregation;
    (function (TermsAggregation) {
        (function (OrderEnum) {
            OrderEnum[OrderEnum["TERMASC"] = 'TERM_ASC'] = "TERMASC";
            OrderEnum[OrderEnum["TERMDESC"] = 'TERM_DESC'] = "TERMDESC";
            OrderEnum[OrderEnum["COUNTASC"] = 'COUNT_ASC'] = "COUNTASC";
            OrderEnum[OrderEnum["COUNTDESC"] = 'COUNT_DESC'] = "COUNTDESC";
        })(TermsAggregation.OrderEnum || (TermsAggregation.OrderEnum = {}));
        var OrderEnum = TermsAggregation.OrderEnum;
    })(TermsAggregation = exports.TermsAggregation || (exports.TermsAggregation = {}));
});
