/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
define(["require", "exports"], function (require, exports) {
    "use strict";
    var User;
    (function (User) {
        (function (TypeEnum) {
            TypeEnum[TypeEnum["Database"] = 'database'] = "Database";
            TypeEnum[TypeEnum["Ldap"] = 'ldap'] = "Ldap";
            TypeEnum[TypeEnum["Token"] = 'token'] = "Token";
            TypeEnum[TypeEnum["Saml"] = 'saml'] = "Saml";
        })(User.TypeEnum || (User.TypeEnum = {}));
        var TypeEnum = User.TypeEnum;
        (function (StatusEnum) {
            StatusEnum[StatusEnum["ACTIVE"] = 'ACTIVE'] = "ACTIVE";
            StatusEnum[StatusEnum["DISABLED"] = 'DISABLED'] = "DISABLED";
            StatusEnum[StatusEnum["REGISTERING"] = 'REGISTERING'] = "REGISTERING";
        })(User.StatusEnum || (User.StatusEnum = {}));
        var StatusEnum = User.StatusEnum;
    })(User = exports.User || (exports.User = {}));
});
