/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface DeviceInfo extends models.Item {
    lastLoginIpAddress?: string;

    roles?: Array<string>;

    lastLoginDate?: models.Date;

    deviceType?: string;

    serialNumber?: string;

    linkedUser?: string;

    activeMacAddress?: string;

    deviceVersion?: string;

    validMacAddress?: string;

    network?: string;

    macAddress?: string;

    extraInformation?: Array<string>;

    model?: string;

    location?: string;

    subLocation?: string;

    frontendVersion?: string;

    frontendSettings?: any;

    status?: string;

}
