/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface FlowrFrontendSettings extends models.Item {
    subtitlesLanguage?: string;

    autoUpdate?: boolean;

    interfaceLanguage?: string;

    lastChannelId?: string;

    bootPageId?: string;

    startVolume?: number;

    audioLanguage?: string;

    location?: any;

    preferredContent?: Array<string>;

    user?: string;

    maxVolume?: number;

}
