/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface FlowrMediaplay extends models.TimestampedItem {
    instanceId?: string;

    replicaId?: string;

    serviceName?: string;

    properties?: { [key: string]: string; };

    totalDuration?: number;

    itemId?: string;

    description?: string;

    userAgent?: string;

    ratioEffectiveTotal?: number;

    url?: string;

    effectivelyPlayedDuration?: number;

}
