/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface LogItem extends models.TimestampedItem {
    instanceId?: string;

    replicaId?: string;

    serviceName?: string;

    properties?: { [key: string]: string; };

    severity?: string;

    stackTrace?: string;

    thread?: string;

    message?: string;

    category?: string;

}
